#!/bin/bash
set -euo pipefail
NDK_DIR="$1"; OUTPUT_DIR="$2"; BUILD_DIR="$3"; API_LEVEL="${4:-24}"
mkdir -p "$BUILD_DIR" && cd "$BUILD_DIR"
git clone --depth 1 --branch v2.3.2 https://github.com/AcademySoftwareFoundation/OpenColorIO.git src
cd src
cmake -B build \
  -DCMAKE_TOOLCHAIN_FILE="$NDK_DIR/build/cmake/android.toolchain.cmake" \
  -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM="android-$API_LEVEL" \
  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$OUTPUT_DIR" \
  -DCMAKE_PREFIX_PATH="$OUTPUT_DIR" \
  -DCMAKE_FIND_ROOT_PATH="$OUTPUT_DIR" \
  -DCMAKE_CXX_FLAGS="-D_GNU_SOURCE -include time.h" \
  -DBUILD_SHARED_LIBS=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
  -DOCIO_BUILD_APPS=OFF -DOCIO_BUILD_TESTS=OFF -DOCIO_BUILD_PYGLUE=OFF \
  -DOCIO_BUILD_GPUDELEGATES=OFF -DOCIO_INSTALL_EXT_DIR=OFF \
  -DOCIO_USE_SSE2=OFF -DOCIO_USE_SSE4=OFF -DOCIO_USE_AVX=OFF -DOCIO_USE_AVX2=OFF \
  -DUSE_PYTHON=OFF \
  -DCMAKE_DISABLE_FIND_PACKAGE_expat=TRUE \
  -DCMAKE_DISABLE_FIND_PACKAGE_yaml-cpp=TRUE \
  -DCMAKE_DISABLE_FIND_PACKAGE_pystring=TRUE \
  -DCMAKE_DISABLE_FIND_PACKAGE_Imath=TRUE \
  -DCMAKE_DISABLE_FIND_PACKAGE_minizip-ng=TRUE \
  -DCMAKE_DISABLE_FIND_PACKAGE_pybind11=TRUE \
  -DCMAKE_DISABLE_FIND_PACKAGE_Python=TRUE
cmake --build build -j$(nproc)
cmake --install build
echo "OpenColorIO built"
